
import React, { useState } from "react";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Textarea } from "@/components/ui/textarea";
import { MetaTagsType } from "@/hooks/useContentOptimizer";
import { ClipboardCopy, Code, Tag, Edit2, Check } from "lucide-react";
import { Badge } from "@/components/ui/badge";
import { toast } from "sonner";

interface MetaTagGeneratorProps {
  metaTags: MetaTagsType;
}

const MetaTagGenerator: React.FC<MetaTagGeneratorProps> = ({ metaTags }) => {
  const [title, setTitle] = useState(metaTags.title);
  const [description, setDescription] = useState(metaTags.description);
  const [keywords, setKeywords] = useState(metaTags.keywords.join(", "));
  const [isEditing, setIsEditing] = useState(false);
  
  React.useEffect(() => {
    if (metaTags.title) setTitle(metaTags.title);
    if (metaTags.description) setDescription(metaTags.description);
    if (metaTags.keywords.length) setKeywords(metaTags.keywords.join(", "));
  }, [metaTags]);
  
  const handleCopyCode = () => {
    const codeSnippet = `<head>
  <!-- Meta Tags Generated by Content Optimizer -->
  <title>${title}</title>
  <meta name="description" content="${description}" />
  <meta name="keywords" content="${keywords}" />
  <meta property="og:title" content="${title}" />
  <meta property="og:description" content="${description}" />
  <meta name="twitter:title" content="${title}" />
  <meta name="twitter:description" content="${description}" />
</head>`;

    navigator.clipboard.writeText(codeSnippet);
    toast.success("Meta tags copied to clipboard");
  };
  
  const getColorsForLength = (text: string, minLength: number, maxLength: number) => {
    if (!text) return "text-gray-400";
    if (text.length < minLength) return "text-yellow-600";
    if (text.length > maxLength) return "text-red-600";
    return "text-green-600";
  };
  
  const getTitleColor = () => getColorsForLength(title, 30, 60);
  const getDescriptionColor = () => getColorsForLength(description, 70, 160);
  
  return (
    <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
      <Card className="w-full">
        <CardHeader>
          <CardTitle className="flex items-center">
            <Tag className="h-5 w-5 mr-2 text-seo-purple" />
            Meta Tag Generator
          </CardTitle>
          <CardDescription>
            Create optimized meta tags for better search engine results
          </CardDescription>
        </CardHeader>
        <CardContent>
          {!metaTags.title && !isEditing ? (
            <div className="text-center py-12 text-gray-500">
              <Tag className="h-12 w-12 mx-auto mb-4 text-gray-300" />
              <p>Analyze your content to generate meta tags</p>
              <Button 
                variant="outline" 
                className="mt-4" 
                onClick={() => setIsEditing(true)}
              >
                <Edit2 className="h-4 w-4 mr-2" />
                Create Manually
              </Button>
            </div>
          ) : isEditing ? (
            <div className="space-y-4">
              <div>
                <label htmlFor="meta-title" className="block text-sm font-medium mb-1">
                  Meta Title <span className="text-xs text-gray-500">(30-60 characters)</span>
                </label>
                <Input
                  id="meta-title"
                  value={title}
                  onChange={(e) => setTitle(e.target.value)}
                  className="font-mono"
                />
                <div className="flex justify-between mt-1 text-xs">
                  <span className={getTitleColor()}>
                    {title.length} characters
                  </span>
                  <span>
                    {title.length < 30 ? "Too short" : 
                     title.length > 60 ? "Too long" : "Good length"}
                  </span>
                </div>
              </div>
              
              <div>
                <label htmlFor="meta-description" className="block text-sm font-medium mb-1">
                  Meta Description <span className="text-xs text-gray-500">(70-160 characters)</span>
                </label>
                <Textarea
                  id="meta-description"
                  value={description}
                  onChange={(e) => setDescription(e.target.value)}
                  className="font-mono"
                  rows={3}
                />
                <div className="flex justify-between mt-1 text-xs">
                  <span className={getDescriptionColor()}>
                    {description.length} characters
                  </span>
                  <span>
                    {description.length < 70 ? "Too short" : 
                     description.length > 160 ? "Too long" : "Good length"}
                  </span>
                </div>
              </div>
              
              <div>
                <label htmlFor="meta-keywords" className="block text-sm font-medium mb-1">
                  Keywords <span className="text-xs text-gray-500">(comma separated)</span>
                </label>
                <Input
                  id="meta-keywords"
                  value={keywords}
                  onChange={(e) => setKeywords(e.target.value)}
                  className="font-mono"
                />
              </div>
              
              <div className="flex justify-end space-x-2 pt-4">
                <Button 
                  variant="outline" 
                  onClick={() => {
                    setTitle(metaTags.title || "");
                    setDescription(metaTags.description || "");
                    setKeywords(metaTags.keywords.join(", ") || "");
                    setIsEditing(false);
                  }}
                >
                  Cancel
                </Button>
                <Button 
                  onClick={() => {
                    setIsEditing(false);
                    toast.success("Meta tags updated");
                  }}
                >
                  <Check className="h-4 w-4 mr-2" />
                  Save Changes
                </Button>
              </div>
            </div>
          ) : (
            <div className="space-y-6">
              <div>
                <h3 className="text-sm font-medium mb-1">Title Tag</h3>
                <div className="p-3 bg-gray-50 rounded-md font-mono text-sm">
                  {title}
                </div>
                <div className="flex justify-between mt-1 text-xs">
                  <span className={getTitleColor()}>
                    {title.length} characters
                  </span>
                  <span>
                    {title.length < 30 ? "Too short" : 
                     title.length > 60 ? "Too long" : "Good length"}
                  </span>
                </div>
              </div>
              
              <div>
                <h3 className="text-sm font-medium mb-1">Meta Description</h3>
                <div className="p-3 bg-gray-50 rounded-md font-mono text-sm min-h-[80px]">
                  {description}
                </div>
                <div className="flex justify-between mt-1 text-xs">
                  <span className={getDescriptionColor()}>
                    {description.length} characters
                  </span>
                  <span>
                    {description.length < 70 ? "Too short" : 
                     description.length > 160 ? "Too long" : "Good length"}
                  </span>
                </div>
              </div>
              
              <div>
                <h3 className="text-sm font-medium mb-1">Keywords</h3>
                <div className="flex flex-wrap gap-2">
                  {keywords.split(",").map((keyword, index) => (
                    <Badge key={index} variant="outline" className="bg-gray-50">
                      {keyword.trim()}
                    </Badge>
                  ))}
                </div>
              </div>
              
              <div className="flex justify-end space-x-2 pt-2">
                <Button 
                  variant="outline" 
                  onClick={() => setIsEditing(true)}
                >
                  <Edit2 className="h-4 w-4 mr-2" />
                  Edit
                </Button>
                <Button onClick={handleCopyCode}>
                  <ClipboardCopy className="h-4 w-4 mr-2" />
                  Copy HTML
                </Button>
              </div>
            </div>
          )}
        </CardContent>
      </Card>
      
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center">
            <Code className="h-5 w-5 mr-2 text-seo-purple" />
            Preview
          </CardTitle>
          <CardDescription>
            See how your meta tags will appear in search results
          </CardDescription>
        </CardHeader>
        <CardContent>
          {!title ? (
            <div className="text-center py-12 text-gray-500">
              <Code className="h-12 w-12 mx-auto mb-4 text-gray-300" />
              <p>Create meta tags to see a preview</p>
            </div>
          ) : (
            <div className="border rounded-md p-4">
              <div className="mb-5">
                <h3 className="text-sm font-medium mb-2">Search Engine Result Preview:</h3>
                <div className="p-4 border rounded">
                  <div className="text-blue-600 text-lg font-medium line-clamp-1">
                    {title}
                  </div>
                  <div className="text-green-800 text-sm my-1 opacity-80">
                    example.com/your-page 
                    <span className="text-gray-500 mx-2">•</span> 
                    <span className="text-gray-600">Cached</span>
                  </div>
                  <div className="text-gray-700 text-sm line-clamp-2">
                    {description || "No description available..."}
                  </div>
                </div>
              </div>
              
              <div className="mb-5">
                <h3 className="text-sm font-medium mb-2">Social Media Card Preview:</h3>
                <div className="border rounded overflow-hidden">
                  <div className="bg-gray-200 h-32 flex items-center justify-center">
                    <span className="text-gray-400">Image Preview</span>
                  </div>
                  <div className="p-3">
                    <div className="font-medium line-clamp-1">{title}</div>
                    <div className="text-sm text-gray-500 line-clamp-2 mt-1">{description}</div>
                    <div className="text-xs text-gray-400 mt-2">example.com</div>
                  </div>
                </div>
              </div>
              
              <div>
                <h3 className="text-sm font-medium mb-2">HTML Code:</h3>
                <div className="p-3 bg-gray-900 rounded-md text-gray-100 font-mono text-xs">
                  <div>&lt;head&gt;</div>
                  <div className="pl-4">&lt;title&gt;{title}&lt;/title&gt;</div>
                  <div className="pl-4">&lt;meta name="description" content="{description}" /&gt;</div>
                  <div className="pl-4">&lt;meta name="keywords" content="{keywords}" /&gt;</div>
                  <div className="pl-4">&lt;meta property="og:title" content="{title}" /&gt;</div>
                  <div className="pl-4">&lt;meta property="og:description" content="{description}" /&gt;</div>
                  <div>&lt;/head&gt;</div>
                </div>
              </div>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
};

export default MetaTagGenerator;
