// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://vikkomfglbzuisdwkaew.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InZpa2tvbWZnbGJ6dWlzZHdrYWV3Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ3MDQ1NTksImV4cCI6MjA2MDI4MDU1OX0.RaIJZzhjalzevVptYNUvDfoKLBvU98TJClVMgaD93lE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);